### ISSUE TITLE
预训练时长

### ISSUE THREAD

**Issue by chensming** [Jeasco/RAHC#4]
您好，我想问下您预训练得到 `cookbook` 这一步用了多少张卡 训了多久
还是您是用 https://github.com/CompVis/taming-transformers 提供的预训练权重呢
> “More precisely, we utilize the VQGAN [11] pre-trained on OpenImages [20] with 8192 quantization encodings as a library of reconstruction vectors.”

**Comment by Jeasco** [comment]
我们是直接用的它们预训练好的权重
